//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/PurchaseOrderSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("PurchaseOrder", Namespace="http://tempuri.org/PurchaseOrderSchema.xsd", IsNullable=false)]
public partial class PurchaseOrderType {
    
    private Adresy[] shipToField;
    
    private Adresy billToField;
    
    private System.DateTime data_zamowieniaField;
    
    private bool data_zamowieniaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShipTo")]
    public Adresy[] ShipTo {
        get {
            return this.shipToField;
        }
        set {
            this.shipToField = value;
        }
    }
    
    /// <remarks/>
    public Adresy BillTo {
        get {
            return this.billToField;
        }
        set {
            this.billToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime Data_zamowienia {
        get {
            return this.data_zamowieniaField;
        }
        set {
            this.data_zamowieniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Data_zamowieniaSpecified {
        get {
            return this.data_zamowieniaFieldSpecified;
        }
        set {
            this.data_zamowieniaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/PurchaseOrderSchema.xsd")]
public partial class Adresy {
    
    private string nazwaField;
    
    private string ulicaField;
    
    private string miastoField;
    
    private string wojewodztwoField;
    
    private string kod_pocztowyField;
    
    private string krajField;
    
    public Adresy() {
        this.krajField = "US";
    }
    
    /// <remarks/>
    public string nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    public string miasto {
        get {
            return this.miastoField;
        }
        set {
            this.miastoField = value;
        }
    }
    
    /// <remarks/>
    public string wojewodztwo {
        get {
            return this.wojewodztwoField;
        }
        set {
            this.wojewodztwoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string kod_pocztowy {
        get {
            return this.kod_pocztowyField;
        }
        set {
            this.kod_pocztowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
    public string kraj {
        get {
            return this.krajField;
        }
        set {
            this.krajField = value;
        }
    }
}
